[package]
name = "embassy-mock"
authors = ["Callum Dunster"]
description = "An unofficial collection of mocked types for the Embassy framework"
license = "MIT"
repository = "https://github.com/cdunster/embassy-mock"
version = "0.0.0"
edition = "2021"
