[package]
name = "embassy-mock"
authors = ["Callum Dunster"]
description = "An unofficial collection of mocked types for the Embassy framework"
license = "MIT"
repository = "https://github.com/cdunster/embassy-mock"
version = "0.4.0"
edition = "2021"

[[example]]
name = "executor"
required-features = ["executor", "examples"]
test = true

[[example]]
name = "ticker"
required-features = ["time", "examples"]
test = true

[[example]]
name = "timer"
required-features = ["time", "examples"]
test = true

[[example]]
name = "concrete-types"
required-features = ["executor", "time", "examples"]
test = true

[dependencies]
embassy-executor = { version = "0.5.0", optional = true }
embassy-time = { version = "0.3.0", optional = true }
snafu = { version = "0.7.5", default-features = false }

[dev-dependencies]
embassy-executor = { version = "0.5.0", features = [
  "arch-std",
  "executor-thread",
  "integrated-timers",
] }
embassy-futures = "0.1.0"
embassy-time = { version = "0.3.0", features = ["std"] }

[features]
default = ["executor", "time"]
executor = ["dep:embassy-executor"]
time = ["dep:embassy-time"]
examples = [
  "dep:embassy-time",
  "embassy-time/std",
  "embassy-executor/executor-thread",
  "embassy-executor/arch-std",
  "embassy-executor/integrated-timers",
]
