# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "nightly-2024-05-01"
components = ["rustfmt", "clippy", "llvm-tools-preview"]
